In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("waterdata.csv", encoding= 'unicode_escape')

In [5]:
dataset.describe()

year
count  1991.000000
mean   2010.038172
std       3.057333
min    2003.000000
25%    2008.000000
50%    2011.000000
75%    2013.000000
max    2014.000000

In [4]:
dataset["Temp"] = pd.to_numeric(dataset['Temp'], errors='coerce')
dataset["Temp"] = dataset["Temp"].replace(np.nan, 0)
dataset["PH"] = pd.to_numeric(dataset['PH'], errors='coerce')
dataset["PH"] = dataset["PH"].replace(np.nan, 0)
dataset["D.O. (mg/l)"] = pd.to_numeric(dataset['D.O. (mg/l)'], errors='coerce')
dataset["D.O. (mg/l)"] = dataset["D.O. (mg/l)"].replace(np.nan, 0)
# dataset["Temp"] = dataset["Temp"].fillna()

In [5]:
y = dataset["D.O. (mg/l)"]

In [6]:
X = dataset[["Temp", "PH"]]

In [7]:
# X["Temp"] = X["Temp"].mean()
# X["Temp"] = X[X["Temp"]==0].mean()

In [8]:
# X["Temp"].mean()
X["PH"].mean()

111.64028478151683

In [9]:
dataset=dataset.mask(dataset["Temp"]==0).fillna(dataset["Temp"].mean())
dataset=dataset.mask(dataset["PH"]==0).fillna(dataset["PH"].mean())
dataset=dataset.mask(dataset["D.O. (mg/l)"]==0).fillna(dataset["D.O. (mg/l)"].mean())

In [10]:
y = dataset["D.O. (mg/l)"]
X = dataset[["Temp", "PH"]]
X["PH"]

0         7.500000
1         7.200000
2         6.900000
3         6.900000
4         7.300000
           ...    
1986     24.998713
1987    585.000000
1988     98.000000
1989     91.000000
1990    110.000000
Name: PH, Length: 1991, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lm = LinearRegression()

In [15]:
lm.fit(X_train, y_train)

LinearRegression()

In [16]:
lm.coef_

array([-7.00139188e-02,  3.22665334e-06])

In [17]:
predictions = lm.predict(X_test)

In [18]:
predictions

array([7.67333562, 7.56831442, 7.07821462, 7.56860288, 7.76435146,
       7.03620896, 6.86817652, 7.28825874, 6.72814707, 6.93819173,
       7.10622417, 7.00820146, 7.56831506, 7.00820275, 7.23224632,
       7.21824547, 7.53330714, 7.0642142 , 7.12022276, 7.28840501,
       7.28840501, 7.35827137, 7.2392461 , 7.07821731, 7.07821312,
       7.00820436, 7.07833444, 7.39328059, 7.32326183, 7.98839609,
       7.56831281, 7.21824418, 7.28825874, 7.33726752, 7.63832802,
       6.93819044, 7.47729762, 7.28840501, 7.00820013, 7.78535628,
       7.21824386, 7.14823155, 7.07821215, 7.07821537, 7.28840501,
       7.12722221, 7.07821731, 6.86817555, 7.3582717 , 7.14823349,
       6.86817652, 7.39327543, 7.00819887, 6.93118776, 7.07821441,
       6.86817588, 7.7783566 , 7.01520543, 7.05020948, 7.00819984,
       7.16223466, 7.21824257, 7.09572087, 7.42828723, 7.00820113,
       7.77835714, 7.08521644, 7.35827266, 7.28825778, 7.00820242,
       7.41428348, 7.70834097, 7.0082021 , 6.9381898 , 7.07821

In [19]:
X_test.shape

(598, 2)

In [25]:
data = {'longitude':  [30.6],
        'latitude': [7.5]}

In [26]:
df = pd.DataFrame (data, columns = ['longitude','latitude'])

In [27]:
df.shape

(1, 2)

In [28]:
answer = lm.predict(df)

In [29]:
answer

array([6.89618048])